---
abstract: 'A modular perl shell'
author:
  - 'Jaap Karssenberg <pardus@cpan.org>'
build_requires:
  Data::Dumper: 0
  Module::Build: 0.28
  Pod::Text: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.28
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Zoidberg
no_index:
  file:
    - b/ModuleBuildZoid.pm
recommends:
  Env::PS1: 0
  Term::ReadLine::Zoid: 0
requires:
  AutoLoader: 0
  Cwd: 0
  Data::Dumper: 0
  Encode: 0
  Env: 0
  Exporter::Tidy: 0
  File::Glob: 0
  File::ShareDir: 1.00
  File::Spec: 0
  POSIX: 0
  Pod::Usage: 0
  Scalar::Util: 0
  perl: v5.6.2
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jberger/Zoidberg
version: 0.97
